<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Algorithms_programm\Algorithms_programm.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controls\" />
      <Folder Include="Resources\" />
      <Folder Include="Services\" />
      <Folder Include="ViewModels\" />
      <Folder Include="Views\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
    </ItemGroup>

</Project>
