// <auto-generated />
using System;
using Algorithms_programm.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Algorithms_programm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922005719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Algorithms_programm.Database.Entities.AlgorithmEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Algorithms");
                });

            modelBuilder.Entity("Algorithms_programm.Database.Entities.ExperimentRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ElapsedMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<int?>("M")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("N")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StepCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "N", "M");

                    b.ToTable("ExperimentRuns");
                });

            modelBuilder.Entity("Algorithms_programm.Database.Entities.ExperimentSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlgorithmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunsPerPoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId", "ConfigHash");

                    b.ToTable("ExperimentSessions");
                });

            modelBuilder.Entity("Algorithms_programm.Database.Entities.ExperimentRunEntity", b =>
                {
                    b.HasOne("Algorithms_programm.Database.Entities.ExperimentSessionEntity", "Session")
                        .WithMany("Runs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Algorithms_programm.Database.Entities.ExperimentSessionEntity", b =>
                {
                    b.HasOne("Algorithms_programm.Database.Entities.AlgorithmEntity", "Algorithm")
                        .WithMany("Sessions")
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Algorithm");
                });

            modelBuilder.Entity("Algorithms_programm.Database.Entities.AlgorithmEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Algorithms_programm.Database.Entities.ExperimentSessionEntity", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
